In [1]:
from sql_interface import SqlData, PickleUpdate
import logging
import pandas as pd
import os
import datetime

# Get an instance of a logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# SqlData example

In [ ]:
data=SqlData()

### stock_price

In [ ]:
test=data.get('stock_price','stock_id,date,vol',limit=60, data_format='pivot',stock_id="('0050','0056')")
test

In [ ]:
test['0050']

In [ ]:
test=data.get('stock_price','stock_id,date,close,open',limit=2, data_format='pivot')
test

In [ ]:
test=data.get('stock_price','stock_id,date,close,open',date_range="('2020-12-1','2020-11-30')", data_format='table')
test

In [ ]:
test=data.get('company_info','stock_id',data_format='table')
test

### monthly_revenue

In [ ]:
test=data.get('monthly_revenue','stock_id,date,this_month_rev,cp_last_month_rev,cp_last_year_rev,cp_cm_rev',limit=120, data_format='table')
test

In [ ]:
test=data.get('monthly_revenue', data_format='table',all_data=True)
test

In [ ]:
test.to_pickle(os.path.dirname(os.path.abspath("__file__"))+'/pickle_table/tw_data/monthly_revenue.pkl')

### tej_fundamental

In [ ]:
test=data.get('tej_fundamental','stock_id,date,股本,營業收入淨額,營業成本,營業毛利,營業費用,營業利益,稅前淨利,稀釋稅後淨利,每股盈餘',all_data=True, data_format='table')
test

### divide_ratio

In [ ]:
test=data.get('stock_divide_ratio','stock_id,date,divide_ratio',all_data=True, data_format='table')
test

# Use SqlData to update pickle

connect sql db

In [2]:
# df=pd.read_pickle(os.path.dirname(os.path.abspath("__file__"))+'/pickle_table/tw_data/stock_price.pkl')
# df
table_path=os.path.dirname(os.path.abspath("__file__"))+'/pickle_table/'
tw_fdata_path=os.path.dirname(os.path.abspath("__file__"))+'/tw_fdata/'

In [ ]:
PickleUpdate().update_pkl(table_path,'tw_data','stock_price',pivot_data_path=tw_fdata_path)

In [3]:
PickleUpdate().update_pkl(table_path,'tw_data','monthly_revenue',pivot_data_path=tw_fdata_path)

INFO:sql_interface:success update tw_data/monthly_revenue.pkl
INFO:sql_interface:divide pivot file:this_month_rev
INFO:sql_interface:divide pivot file:last_month_rev
INFO:sql_interface:divide pivot file:last_year_rev
INFO:sql_interface:divide pivot file:cp_last_month_rev
INFO:sql_interface:divide pivot file:cp_last_year_rev
INFO:sql_interface:divide pivot file:cm_this_month_rev
INFO:sql_interface:divide pivot file:cm_last_year_rev
INFO:sql_interface:divide pivot file:cp_cm_rev

In [4]:
PickleUpdate().update_pkl(table_path,'tw_data','tej_fundamental',pivot_data_path=tw_fdata_path)

INFO:sql_interface:success update tw_data/tej_fundamental.pkl
INFO:sql_interface:divide pivot file:現金及約當現金
INFO:sql_interface:divide pivot file:透過損益按公允價值衡量之金融資產_流動
INFO:sql_interface:divide pivot file:合約資產_流動
INFO:sql_interface:divide pivot file:應收帳款及票據
INFO:sql_interface:divide pivot file:其他應收款
INFO:sql_interface:divide pivot file:資金貸予他人_流動
INFO:sql_interface:divide pivot file:存貨
INFO:sql_interface:divide pivot file:待出售非流動資產
INFO:sql_interface:divide pivot file:當期所得稅資產_流動
INFO:sql_interface:divide pivot file:流動資產
INFO:sql_interface:divide pivot file:按攤銷後成本衡量之金融資產_非流動
INFO:sql_interface:divide pivot file:採權益法之長期股權投資
INFO:sql_interface:divide pivot file:預付投資款
INFO:sql_interface:divide pivot file:不動產廠房及設備
INFO:sql_interface:divide pivot file:商譽及無形資產合計
INFO:sql_interface:divide pivot file:遞延所得稅資產
INFO:sql_interface:divide pivot file:投資性不動產淨額
INFO:sql_interface:divide pivot file:其他非流動資產
INFO:sql_interface:divide pivot file:非流動資產
INFO:sql_interface:divide pivot file:資產總額
INFO:sql_interface:divide pivot file:短期借款
INFO:sql_interface:divide pivot file:透過損益按公允價值衡量之金融負債_流動
INFO:sql_interface:divide pivot file:合約負債_流動
INFO:sql_interface:divide pivot file:應付帳款及票據
INFO:sql_interface:divide pivot file:其他應付款
INFO:sql_interface:divide pivot file:當期所得稅負債
INFO:sql_interface:divide pivot file:與待出售非流動資產直接相關之負債
INFO:sql_interface:divide pivot file:一年內到期長期負債
INFO:sql_interface:divide pivot file:流動負債
INFO:sql_interface:divide pivot file:透過損益按公允價值衡量之金融負債_非流動
INFO:sql_interface:divide pivot file:應付公司債_非流動
INFO:sql_interface:divide pivot file:銀行借款_非流動
INFO:sql_interface:divide pivot file:負債準備_非流動
INFO:sql_interface:divide pivot file:應計退休金負債
INFO:sql_interface:divide pivot file:遞延所得稅
INFO:sql_interface:divide pivot file:非流動負債
INFO:sql_interface:divide pivot file:負債總額
INFO:sql_interface:divide pivot file:股本
INFO:sql_interface:divide pivot file:資本公積合計
INFO:sql_interface:divide pivot file:法定盈餘公積
INFO:sql_interface:divide pivot file:特別盈餘公積
INFO:sql_interface:divide pivot file:未分配盈餘
INFO:sql_interface:divide pivot file:保留盈餘
INFO:sql_interface:divide pivot file:其他權益
INFO:sql_interface:divide pivot file:庫藏股票帳面值
INFO:sql_interface:divide pivot file:母公司股東權益合計
INFO:sql_interface:divide pivot file:共同控制下前手權益
INFO:sql_interface:divide pivot file:合併前非屬共同控制股權
INFO:sql_interface:divide pivot file:非控制權益
INFO:sql_interface:divide pivot file:股東權益總額
INFO:sql_interface:divide pivot file:負債及股東權益總額
INFO:sql_interface:divide pivot file:營業收入淨額
INFO:sql_interface:divide pivot file:營業成本
INFO:sql_interface:divide pivot file:營業毛利
INFO:sql_interface:divide pivot file:營業費用
INFO:sql_interface:divide pivot file:研究發展費
INFO:sql_interface:divide pivot file:預期信用減損_損失_利益_營業費用
INFO:sql_interface:divide pivot file:營業利益
INFO:sql_interface:divide pivot file:其他收入
INFO:sql_interface:divide pivot file:其他利益及損失
INFO:sql_interface:divide pivot file:財務成本
INFO:sql_interface:divide pivot file:採權益法之關聯企業及合資損益之份額
INFO:sql_interface:divide pivot file:預期信用減損_損失_利益
INFO:sql_interface:divide pivot file:除列按攤銷後成本衡量金融資產淨損益
INFO:sql_interface:divide pivot file:金融資產重分類淨損益
INFO:sql_interface:divide pivot file:營業外收入及支出_其他
INFO:sql_interface:divide pivot file:營業外收入及支出
INFO:sql_interface:divide pivot file:稅前淨利
INFO:sql_interface:divide pivot file:所得稅費用
INFO:sql_interface:divide pivot file:繼續營業單位損益
INFO:sql_interface:divide pivot file:停業單位損益
INFO:sql_interface:divide pivot file:合併前非屬共同控制股權損益
INFO:sql_interface:divide pivot file:其他損益調整項_非常項目及累計影響數
INFO:sql_interface:divide pivot file:合併總損益
INFO:sql_interface:divide pivot file:其他綜合損益_oci
INFO:sql_interface:divide pivot file:本期綜合損益總額
INFO:sql_interface:divide pivot file:歸屬母公司淨利_損
INFO:sql_interface:divide pivot file:歸屬非控制權益淨利_損
INFO:sql_interface:divide pivot file:歸屬共同控制下前手權益淨利_損
INFO:sql_interface:divide pivot file:綜合損益歸屬母公司
INFO:sql_interface:divide pivot file:綜合損益歸屬非控制權益
INFO:sql_interface:divide pivot file:綜合損益歸屬共同控制下前手權益
INFO:sql_interface:divide pivot file:每股盈餘
INFO:sql_interface:divide pivot file:加權平均股數
INFO:sql_interface:divide pivot file:發放特別股股息
INFO:sql_interface:divide pivot file:稀釋稅後淨利
INFO:sql_interface:divide pivot file:每股盈餘_完全稀釋
INFO:sql_interface:divide pivot file:加權平均股數_稀釋
INFO:sql_interface:divide pivot file:稅前息前淨利
INFO:sql_interface:divide pivot file:稅前息前折舊前淨利
INFO:sql_interface:divide pivot file:常續性稅後淨利
INFO:sql_interface:divide pivot file:期末普通股_現金股利
INFO:sql_interface:divide pivot file:期末普通股_股票股利
INFO:sql_interface:divide pivot file:普通股每股現金股利_盈餘及公積
INFO:sql_interface:divide pivot file:普通股每股現金股利_盈餘
INFO:sql_interface:divide pivot file:普通股每股現金股利_公積
INFO:sql_interface:divide pivot file:普通股每股股票股利_盈餘
INFO:sql_interface:divide pivot file:普通股每股股票股利_公積
INFO:sql_interface:divide pivot file:資本公積_現金股利
INFO:sql_interface:divide pivot file:資本公積轉增資_股票股利
INFO:sql_interface:divide pivot file:稅前淨利_cfo
INFO:sql_interface:divide pivot file:折舊_cfo
INFO:sql_interface:divide pivot file:攤提_cfo
INFO:sql_interface:divide pivot file:來自營運之現金流量
INFO:sql_interface:divide pivot file:新增投資_cfi
INFO:sql_interface:divide pivot file:出售投資_cfi
INFO:sql_interface:divide pivot file:購置不動產廠房設備_含預付_cfi
INFO:sql_interface:divide pivot file:處分不動產廠房設備_含預付_cfi
INFO:sql_interface:divide pivot file:投資活動之現金流量
INFO:sql_interface:divide pivot file:現金增_減_資_cff
INFO:sql_interface:divide pivot file:支付現金股利_cff
INFO:sql_interface:divide pivot file:籌資活動之現金流量
INFO:sql_interface:divide pivot file:匯率影響數
INFO:sql_interface:divide pivot file:本期產生現金流量
INFO:sql_interface:divide pivot file:期初現金及約當現金
INFO:sql_interface:divide pivot file:期末現金及約當現金
INFO:sql_interface:divide pivot file:預計稅額扣抵比率
INFO:sql_interface:divide pivot file:稅額扣抵比率
INFO:sql_interface:divide pivot file:bs透過損益按公允價值衡量之金融資產_流動_ifrs
INFO:sql_interface:divide pivot file:bs持有至到期日金融資產_非流動
INFO:sql_interface:divide pivot file:bs透過損益按公允價值衡量之金融負債_流動_ifrs
INFO:sql_interface:divide pivot file:bs應付建造合約款
INFO:sql_interface:divide pivot file:bs以成本衡量之金融負債_非流動
INFO:sql_interface:divide pivot file:roa_c_稅前息前折舊前
INFO:sql_interface:divide pivot file:roa_a_稅後息前
INFO:sql_interface:divide pivot file:roa_b_稅後息前折舊前
INFO:sql_interface:divide pivot file:roa_綜合損益
INFO:sql_interface:divide pivot file:roe_a_稅後
INFO:sql_interface:divide pivot file:稅前息前折舊前淨利率
INFO:sql_interface:divide pivot file:roe_b_常續利益
INFO:sql_interface:divide pivot file:roe_綜合損益
INFO:sql_interface:divide pivot file:營業毛利率
INFO:sql_interface:divide pivot file:已實現銷貨毛利率
INFO:sql_interface:divide pivot file:營業利益率
INFO:sql_interface:divide pivot file:稅前淨利率
INFO:sql_interface:divide pivot file:稅後淨利率
INFO:sql_interface:divide pivot file:業外收支_營收
INFO:sql_interface:divide pivot file:常續利益率_稅後
INFO:sql_interface:divide pivot file:貝里比率
INFO:sql_interface:divide pivot file:營業資產報酬率
INFO:sql_interface:divide pivot file:員工人數
INFO:sql_interface:divide pivot file:營業費用率
INFO:sql_interface:divide pivot file:用人費用率
INFO:sql_interface:divide pivot file:研究發展費用率
INFO:sql_interface:divide pivot file:呆帳費用率
INFO:sql_interface:divide pivot file:現金流量比率
INFO:sql_interface:divide pivot file:有息負債利率
INFO:sql_interface:divide pivot file:稅率_a
INFO:sql_interface:divide pivot file:稅率_b
INFO:sql_interface:divide pivot file:每股淨值_b
INFO:sql_interface:divide pivot file:每股淨值_a
INFO:sql_interface:divide pivot file:每股淨值_c
INFO:sql_interface:divide pivot file:每股淨值_f_tse公告數
INFO:sql_interface:divide pivot file:常續性eps
INFO:sql_interface:divide pivot file:每股現金流量
INFO:sql_interface:divide pivot file:每股營業額
INFO:sql_interface:divide pivot file:每股營業利益
INFO:sql_interface:divide pivot file:每股稅前淨利
INFO:sql_interface:divide pivot file:每股綜合損益
INFO:sql_interface:divide pivot file:季底每股稅前淨利
INFO:sql_interface:divide pivot file:季底每股稅後淨利
INFO:sql_interface:divide pivot file:營收成長率
INFO:sql_interface:divide pivot file:營業毛利成長率
INFO:sql_interface:divide pivot file:已實現銷貨毛利成長率
INFO:sql_interface:divide pivot file:營業利益成長率
INFO:sql_interface:divide pivot file:稅前淨利成長率
INFO:sql_interface:divide pivot file:稅後淨利成長率
INFO:sql_interface:divide pivot file:經常淨利成長率
INFO:sql_interface:divide pivot file:常續淨利成長率
INFO:sql_interface:divide pivot file:總資產成長率
INFO:sql_interface:divide pivot file:淨值成長率
INFO:sql_interface:divide pivot file:折舊性fa成長率
INFO:sql_interface:divide pivot file:總資產報酬成長率
INFO:sql_interface:divide pivot file:營收變動率
INFO:sql_interface:divide pivot file:營業利益變動率
INFO:sql_interface:divide pivot file:淨利變動率_單季

INFO:sql_interface:divide pivot file:稅前盈餘變動率
INFO:sql_interface:divide pivot file:現金流量允當比
INFO:sql_interface:divide pivot file:現金再投資比
INFO:sql_interface:divide pivot file:流動比率
INFO:sql_interface:divide pivot file:速動比率
INFO:sql_interface:divide pivot file:利息支出率
INFO:sql_interface:divide pivot file:利息支出率_b
INFO:sql_interface:divide pivot file:總負債_總淨值
INFO:sql_interface:divide pivot file:負債比率
INFO:sql_interface:divide pivot file:淨值_資產
INFO:sql_interface:divide pivot file:長期資金適合率_a
INFO:sql_interface:divide pivot file:長短期借款
INFO:sql_interface:divide pivot file:借款依存度
INFO:sql_interface:divide pivot file:或有負債_淨值
INFO:sql_interface:divide pivot file:利息保障倍數
INFO:sql_interface:divide pivot file:內部保留比率
INFO:sql_interface:divide pivot file:營運資金
INFO:sql_interface:divide pivot file:股利支付率
INFO:sql_interface:divide pivot file:存貨及應收帳款_淨值
INFO:sql_interface:divide pivot file:應收帳款週轉次數
INFO:sql_interface:divide pivot file:總資產週轉次數
INFO:sql_interface:divide pivot file:平均收帳天數
INFO:sql_interface:divide pivot file:存貨週轉率_次
INFO:sql_interface:divide pivot file:平均售貨天數
INFO:sql_interface:divide pivot file:固定資產週轉次數
INFO:sql_interface:divide pivot file:淨值週轉率_次
INFO:sql_interface:divide pivot file:應付帳款付現天數
INFO:sql_interface:divide pivot file:淨營業週期_日
INFO:sql_interface:divide pivot file:季底收款天數
INFO:sql_interface:divide pivot file:季底售貨天數
INFO:sql_interface:divide pivot file:自由現金流量_d
INFO:sql_interface:divide pivot file:營運槓桿度
INFO:sql_interface:divide pivot file:財務槓桿度
INFO:sql_interface:divide pivot file:每人營收
INFO:sql_interface:divide pivot file:每人營業利益
INFO:sql_interface:divide pivot file:每人配備率
INFO:sql_interface:divide pivot file:季底普通股市值
INFO:sql_interface:divide pivot file:當季季底p_e
INFO:sql_interface:divide pivot file:當季季底p_b
INFO:sql_interface:divide pivot file:當季季底psr
INFO:sql_interface:divide pivot file:股利殖利率
INFO:sql_interface:divide pivot file:現金股利率
INFO:sql_interface:divide pivot file:透過其他綜合損益按公允價值衡量之金融資產_流動
INFO:sql_interface:divide pivot file:按攤銷後成本衡量之金融資產_流動
INFO:sql_interface:divide pivot file:避險之金融資產_流動
INFO:sql_interface:divide pivot file:透過損益按公允價值衡量之金融資產_非流動
INFO:sql_interface:divide pivot file:透過其他綜合損益按公允價值衡量之金融資產_非流動
INFO:sql_interface:divide pivot file:避險之金融資產_非流動
INFO:sql_interface:divide pivot file:合約資產_非流動
INFO:sql_interface:divide pivot file:遞延資產合計
INFO:sql_interface:divide pivot file:使用權資產
INFO:sql_interface:divide pivot file:應付商業本票_承兌匯票
INFO:sql_interface:divide pivot file:避險之金融負債_流動
INFO:sql_interface:divide pivot file:按攤銷後成本衡量之金融負債_流動
INFO:sql_interface:divide pivot file:負債準備_流動
INFO:sql_interface:divide pivot file:租賃負債_流動
INFO:sql_interface:divide pivot file:特別股負債_流動
INFO:sql_interface:divide pivot file:避險之金融負債_非流動
INFO:sql_interface:divide pivot file:按攤銷後成本衡量之金融負債_非流動
INFO:sql_interface:divide pivot file:合約負債_非流動
INFO:sql_interface:divide pivot file:特別股負債_非流動
INFO:sql_interface:divide pivot file:其他長期借款_非流動
INFO:sql_interface:divide pivot file:租賃負債_非流動
INFO:sql_interface:divide pivot file:遞延貸項
INFO:sql_interface:divide pivot file:普通股股本
INFO:sql_interface:divide pivot file:特別股股本
INFO:sql_interface:divide pivot file:預收股款
INFO:sql_interface:divide pivot file:待分配股票股利
INFO:sql_interface:divide pivot file:換股權利證書
INFO:sql_interface:divide pivot file:聯屬公司已_未_實現銷貨利益
INFO:sql_interface:divide pivot file:已實現銷貨毛利
INFO:sql_interface:divide pivot file:其他收益及費損淨額
INFO:sql_interface:divide pivot file:利息收入
INFO:sql_interface:divide pivot file:不重分類至損益之項目_oci
INFO:sql_interface:divide pivot file:後續可能重分類至損益之項目_oci
INFO:sql_interface:divide pivot file:合併前非屬共同控制股權綜合損益淨額_oci
INFO:sql_interface:divide pivot file:期中普通股_現金股利
INFO:sql_interface:divide pivot file:期中普通股_股票股利
INFO:sql_interface:divide pivot file:期中特別股_現金股利
INFO:sql_interface:divide pivot file:期中特別股_股票股利
INFO:sql_interface:divide pivot file:期末特別股_現金股利
INFO:sql_interface:divide pivot file:期末特別股_股票股利
INFO:sql_interface:divide pivot file:淨負債
INFO:sql_interface:divide pivot file:營業利益_實收資本比
INFO:sql_interface:divide pivot file:稅前純益_實收資本
INFO:sql_interface:divide pivot file:季底應收帳款_營收tse
INFO:sql_interface:divide pivot file:季底存貨_營收tse

In [ ]:
df=pd.read_pickle(os.path.dirname(os.path.abspath("__file__"))+'/pickle_table/tw_data/stock_price.pkl')

In [ ]:
# df.to_pickle(os.path.dirname(os.path.abspath("__file__"))+'/pickle_table/tw_data/stock_price.pkl')

In [ ]:
df_cols = df.columns
cols = [i for i in df_cols if i not in ['stock_id', 'date', 'index','id']]
for c in cols:
    if str(df[c].dtype) in ['float64','int64']:
        print(c)
        pivot_df = pd.pivot_table(df, index=['date'], columns=['stock_id'], values=c,aggfunc='first')
        pivot_df.to_pickle(tw_fdata_path+f'/{c}.pkl')

In [ ]:
'id' in df.columns

In [ ]:
pd.pivot_table(df, index=['date'], columns=['stock_id'], values='vol')

In [ ]:
cols

In [ ]:
df[cols].dtypes.values.astype(str)

In [5]:
ccc=pd.read_pickle('/Users/benbilly3/finlab/sql_interface/tw_fdata/總負債_總淨值.pkl')
ccc

stock_id,000116,000930,000960,0009A0,1101,1102,1103,1104,1107,1108,...,OTC28,OTC30,OTC32,OTC88,OTC89,OTC99,Y5555,Y8886,Y8888,Y9999
date,,,,,,,,,,,,,,,,,,,,,
2005-08-31,132.79,130.94,104.19,161.95,146.26,86.87,142.21,67.95,4570.16,118.58,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-03-31,245.07,133.11,111.56,181.68,136.49,80.92,140.16,68.05,2445.45,110.03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-08-31,257.59,145.94,101.31,213.17,135.46,85.07,95.83,64.40,1541.33,108.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-03-31,276.09,115.79,100.10,234.36,108.14,72.33,84.92,58.96,8456.20,105.94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-08-31,249.86,144.18,106.46,234.04,106.85,76.48,77.29,61.12,22584.53,118.95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-03-31,217.80,119.79,96.39,187.11,86.53,67.98,59.94,58.00,2573.22,127.06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-04-30,167.91,110.63,59.80,132.66,88.18,74.17,52.48,59.02,1783.97,115.85,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-08-31,202.90,127.72,74.39,182.24,105.78,88.73,55.11,64.87,1369.69,124.96,...,438.45,176.95,NaN,107.48,100.50,136.93,505.92,108.51,102.05,315.11
2008-10-31,123.36,53.72,40.20,78.68,108.59,88.71,60.91,66.58,1132.82,131.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-03-31,142.06,76.93,55.63,152.87,107.06,86.82,65.12,68.92,1003.47,135.52,...,457.73,194.47,NaN,104.33,96.15,135.91,537.87,105.23,94.96,322.63
2009-04-30,70.20,61.27,39.35,74.38,107.50,85.68,64.97,69.22,906.85,132.52,...,413.50,180.98,NaN,89.67,94.01,119.34,537.86,100.25,92.45,331.01
2009-08-31,114.96,74.48,64.62,129.75,108.52,88.50,59.09,62.50,824.67,129.11,...,376.52,178.73,NaN,85.79,93.05,116.33,550.04,101.86,96.22,337.83
2009-10-31,77.43,75.40,62.47,126.31,102.87,81.51,59.15,61.65,757.36,124.73,...,334.25,156.67,NaN,82.92,84.68,111.93,526.40,88.70,89.06,322.76
2010-03-31,107.38,117.71,71.49,180.88,102.49,85.91,57.81,60.17,706.09,114.93,...,358.60,205.54,NaN,78.56,86.17,110.24,519.63,91.99,90.26,319.53
2010-04-30,83.14,83.15,55.11,125.21,113.74,89.82,58.81,54.40,658.47,114.00,...,377.11,224.70,NaN,79.29,85.05,111.16,508.95,90.32,88.68,311.17
2010-08-31,114.52,102.17,110.34,191.80,125.85,103.62,70.90,56.65,615.65,118.93,...,377.17,222.65,NaN,89.96,91.71,120.43,532.44,100.68,103.27,336.94
2010-10-31,101.57,102.01,88.27,140.83,111.37,86.84,69.30,37.29,579.22,119.27,...,408.80,260.79,NaN,85.18,87.48,120.04,516.79,91.57,96.55,325.78
2011-03-31,114.53,138.86,104.34,233.36,110.39,85.10,65.45,36.72,536.81,119.81,...,378.17,233.87,NaN,89.81,91.78,120.70,513.72,88.62,94.49,324.96
2011-04-30,79.52,112.10,81.13,160.31,101.59,82.24,56.54,33.86,505.01,124.61,...,355.51,216.11,NaN,89.04,92.99,117.16,498.69,87.32,93.43,317.36
2011-08-31,117.36,122.33,96.06,239.01,108.51,97.24,54.73,37.57,462.19,126.77,...,353.07,219.03,NaN,100.43,97.29,128.20,531.51,102.19,111.27,344.80
2011-10-31,82.32,106.27,62.50,146.94,108.72,96.75,68.32,27.91,441.74,125.12,...,353.08,217.01,NaN,89.83,86.44,118.60,536.39,99.14,108.17,345.46
2012-03-31,118.25,90.74,58.80,227.97,102.52,89.15,67.81,20.26,459.94,119.47,...,335.81,191.45,NaN,83.46,89.96,111.02,500.02,97.96,104.14,321.72
2012-04-30,143.47,130.67,90.40,239.70,91.56,84.55,65.87,20.13,437.70,113.40,...,378.22,254.95,NaN,85.32,91.21,117.76,502.38,99.99,107.84,325.69
2012-08-31,124.95,109.13,72.39,261.66,104.92,100.51,78.45,23.52,418.02,116.11,...,344.72,243.85,NaN,96.50,151.90,129.03,531.86,115.46,122.16,348.82
2012-10-31,132.14,129.31,88.55,281.75,96.05,92.50,83.29,20.18,NaN,107.39,...,329.52,230.84,NaN,92.03,143.50,123.78,518.19,110.00,114.60,338.20
2013-03-31,137.96,123.99,85.98,261.50,93.18,63.55,78.22,20.12,389.88,107.93,...,323.97,220.23,NaN,88.12,142.56,119.53,499.77,104.44,108.76,328.36
2013-05-15,120.72,152.75,71.58,237.84,87.69,69.99,76.73,19.34,NaN,100.20,...,463.96,284.29,NaN,81.79,136.42,105.83,521.48,103.02,103.59,335.21
2013-08-14,110.08,162.30,77.46,237.71,96.52,83.07,77.89,24.41,365.15,101.03,...,470.77,294.03,NaN,90.71,141.29,114.98,543.42,110.14,110.64,351.67
2013-11-14,101.96,155.29,86.37,272.72,87.33,73.01,69.94,22.18,NaN,98.12,...,451.85,281.11,NaN,84.30,124.72,107.57,532.22,107.12,106.88,347.02
2014-03-31,108.58,159.82,89.68,273.04,84.01,71.68,55.24,22.06,343.29,94.92,...,438.75,252.70,NaN,82.32,121.76,104.42,516.66,101.55,105.41,340.01
2014-05-15,112.51,174.09,87.68,286.02,80.57,67.07,58.50,21.14,NaN,88.33,...,458.95,296.96,42.22,75.97,112.90,97.95,522.86,105.36,100.66,337.30
2014-08-14,125.34,172.47,100.35,323.46,90.25,79.19,78.12,25.57,575.67,91.45,...,446.13,256.30,46.53,86.28,130.58,107.84,546.98,113.68,108.91,356.96
2014-11-14,115.47,164.34,114.80,343.08,84.23,73.49,77.19,22.37,NaN,86.63,...,466.12,300.89,49.53,81.23,129.11,103.60,548.40,109.35,105.04,353.00
2015-03-31,107.09,151.74,123.27,340.30,80.69,74.87,74.60,22.69,643.10,81.22,...,444.91,269.93,48.23,77.73,111.39,98.60,524.27,105.38,102.44,334.27
2015-05-15,121.42,175.55,154.18,398.74,78.64,71.99,74.69,22.39,NaN,72.02,...,462.67,284.96,61.52,74.12,110.45,95.48,518.49,109.99,97.07,324.04
2015-08-14,121.90,164.18,166.76,383.19,98.64,78.82,81.80,26.76,733.44,78.50,...,474.28,300.39,64.28,85.44,137.94,107.36,544.43,119.28,108.04,345.02
2015-11-14,115.27,187.48,161.44,346.32,88.25,79.46,110.07,23.45,NaN,68.08,...,489.45,326.79,64.61,80.48,126.34,102.88,549.75,115.43,104.12,343.90
2016-03-31,122.37,152.55,167.55,373.48,88.49,74.41,94.95,24.81,1543.92,62.11,...,472.00,317.62,75.27,77.01,119.06,98.48,541.61,104.02,94.34,334.65
2016-05-15,125.69,146.57,193.23,386.88,80.18,75.00,91.76,23.55,NaN,56.53,...,490.62,357.76,76.64,73.12,110.16,95.09,531.58,101.33,88.38,325.14
2016-08-14,157.61,164.85,204.58,412.86,83.12,75.15,97.14,28.04,105212.40,64.62,...,501.34,361.68,81.80,81.37,124.30,104.19,559.18,110.50,100.66,350.47
2016-11-14,177.99,193.74,196.16,453.22,82.24,71.21,63.30,24.06,NaN,63.48,...,518.65,379.32,80.83,78.76,119.33,103.05,545.08,103.47,97.94,345.93
2017-03-31,154.02,208.32,210.90,473.80,81.14,69.53,65.23,24.10,8759.93,61.45,...,504.47,334.79,78.21,81.01,116.43,103.46,543.64,101.22,95.74,340.32
2017-05-15,161.23,237.87,212.26,535.23,75.91,75.29,53.92,23.93,NaN,58.16,...,488.36,311.66,74.33,79.31,109.31,100.52,539.56,96.89,88.15,331.95
2017-08-14,158.01,258.75,256.90,509.44,80.34,80.08,48.63,29.03,NaN,61.43,...,492.77,336.75,82.96,87.32,124.93,108.59,562.22,107.00,101.09,353.40
2017-11-14,173.12,294.58,262.39,499.45,76.15,70.98,46.93,25.71,NaN,59.66,...,519.90,347.12,71.66,81.52,121.92,103.77,558.70,99.13,97.29,352.53
2018-03-31,174.63,280.84,269.26,474.43,78.55,69.46,47.02,23.75,NaN,63.41,...,515.55,317.99,78.42,83.23,117.96,103.03,545.87,96.66,97.77,346.30
2018-05-15,147.04,303.89,244.45,444.75,70.78,68.13,47.27,23.25,NaN,62.24,...,458.43,279.67,74.28,79.87,120.66,98.23,529.06,96.74,89.68,335.30
2018-08-14,178.32,335.81,319.61,462.81,86.44,67.48,47.82,27.74,NaN,62.04,...,484.36,294.00,83.79,91.57,130.78,111.11,566.44,109.39,102.98,361.26
2018-11-14,187.46,261.25,268.59,414.03,66.10,75.31,43.73,25.24,NaN,65.24,...,489.81,286.73,71.27,85.51,124.55,105.63,559.68,103.10,101.29,359.94
2019-03-31,180.49,215.80,247.12,328.19,74.33,75.54,52.90,26.63,NaN,72.55,...,484.29,290.60,73.77,81.77,121.41,101.22,577.66,104.29,98.73,360.43
2019-05-15,192.92,246.42,274.90,366.65,73.93,72.87,59.25,26.75,NaN,78.16,...,494.79,317.02,106.86,85.11,116.16,104.47,557.63,107.90,94.64,349.14
2019-08-14,215.00,263.11,284.03,373.29,88.21,81.83,60.20,31.65,NaN,75.09,...,521.14,338.10,122.60,97.75,125.73,118.47,583.36,120.58,108.73,374.58
2019-11-14,212.73,252.19,274.64,344.08,80.66,75.27,58.59,28.74,NaN,73.37,...,508.17,307.32,109.29,91.66,113.00,112.08,579.75,116.86,107.03,372.86
2020-03-31,198.70,265.60,270.75,352.64,76.28,75.44,63.54,29.27,NaN,69.61,...,503.77,305.27,105.38,88.16,113.59,108.34,579.06,116.25,103.40,368.22
2020-05-15,207.67,456.49,250.00,382.61,73.26,82.98,68.96,28.97,NaN,72.73,...,533.48,367.68,107.14,90.96,116.91,113.03,626.22,121.18,104.46,387.08
2020-08-14,206.10,431.95,296.19,358.75,95.71,85.73,70.68,32.98,NaN,68.66,...,520.97,348.77,119.74,99.10,127.12,120.97,627.04,127.91,112.80,395.71
2020-11-14,207.36,463.13,274.18,360.74,82.78,81.21,63.28,29.07,NaN,71.91,...,360.26,360.26,101.29,91.39,118.12,97.62,373.69,120.70,110.32,233.65

In [ ]:
str(df['stock_name'].dtype) in ['float64','int64']